### ISSUE TITLE
BackGround 구현

### ISSUE THREAD

**Issue by PangKiYeon** [Project-In-Sadang/MadeleineLove#14]
## 📝 Description
globals.css 를 통해 전역 배경 style을 정의하고
2가지 style 의 배경 컴포넌트 구현하기

## 📌 To-do
- [x] globals.css 를 통해 전역 배경 style을 정의
- [x] 배경 컴포넌트 구현 (1)
- [x] 배경 컴포넌트 구현 (2)
