### ISSUE TITLE
채우기 API TDD

### ISSUE THREAD

**Issue by susooo** [Project-In-Sadang/MadeleineLove#15]
## 📝 Description
WhitePostController와 WhitePostService 클래스의 기능을 테스트하는 테스트입니다. 이 테스트를 통해 각 클래스의 메서드가 올바르게 동작하는지 검증합니다.
- **WhitePostControllerTest**: WhitePostController의 엔드포인트를 테스트합니다. 주로 HTTP 요청을 모의하고, 예상되는 응답을 검증하는 작업을 수행합니다.
- **WhitePostServiceTest**: WhitePostService의 비즈니스 로직을 테스트합니다. 주로 서비스 메서드가 올바르게 동작하는지 검증합니다.

## 📌 To-do
**WhitePostControllerTest**
- [x] long 닉네임 예외 처리
- [x] null content 예외 처리
- [x] empty content 예외 처리
- [x] blank content 예외 처리
- [x] long content 예외 처리
- [x] null method 예외 처리

**WhitePostServiceTest**
- [x] 정상적인 WhitePost 저장
- [x] null 닉네임 설정 성공
- [x] empty 닉네임 설정 성공
- [x] blank 닉네임 설정 성공

## 🔍 ETC
JUnit4.13.1 + MockMvc + Mockito
