### ISSUE TITLE
프론트엔드 개발 환경 구축하기

### ISSUE THREAD

**Issue by PangKiYeon** [Project-In-Sadang/MadeleineLove#3]
## 📝 Description
프론트엔드 개발 환경 구축

## 📌 To-do
- [x] next js 프로젝트 생성 및 기본 설정 하기
- [x] tailwind css 기본 설정 하기
- [x] recoil , React Query 기본 설정 하기

## 🔍 ETC
[참고]
https://velog.io/@ichenny/Next.js-13-TypeScript-Recoil-React-Query-Tailwind-ESlint-Prettier-Yarn-Berry로-초기세팅하기프로젝트-2일차
